Update JENKINSFILE_agentes

diff --git a/JENKINSFILE_agentes b/JENKINSFILE_agentes
--- a/JENKINSFILE_agentes
+++ b/JENKINSFILE_agentes
@@ -1,30 +1,34 @@
 pipeline {
-    agent any
+    agent none
 
-     stages {
-        /// Etapa para las pruebas de código estático con flake8
-        /// Si se encuentran entre 8 y 9 hallazgos, la etapa y el build se marcan como unstable (naranja)
-        /// Si se encuentran 10 o más hallazgos, la etapa y el build se marcan como unhealty (rojo)
-        /// Sea cual sea el resultado, el pipeline continua la ejecución del resto de etapas.
-        /// Pasos:
-        /// 1. Se lanza flake8 y se guardan los resultado en el fichero flake8.out. Se añade exit-zero para que flake8 termine correctamente aunque falle.
-        /// 2. Con recordIssues del plugin Warnings-NG se aplican los qualityGates.
-        
-        stage('Static') {
-            steps {
-                sh '''
-                    export PYTHONPATH=$WORKSPACE
-                    flake8 --exit-zero --format=pylint app > flake8.out
-                '''
-                recordIssues qualityGates: [[integerThreshold: 8, threshold: 8.0, type: 'TOTAL'], [criticality: 'FAILURE', integerThreshold: 10, threshold: 10.0, type: 'TOTAL']], sourceCodeRetention: 'LAST_BUILD', tools: [flake8(pattern: 'flake8.out')]
-            }
-        }
-        
+    stages {
         /// Etapa para lanzar las pruebas unitarias y de integración paralelamente
-        stage('Tests')
-        {
-            parallel
-            {
+        stage('Tests') {
+            parallel {
+
+                /// Etapa para las pruebas de código estático con flake8
+                /// Si se encuentran entre 8 y 9 hallazgos, la etapa y el build se marcan como unstable (naranja)
+                /// Si se encuentran 10 o más hallazgos, la etapa y el build se marcan como unhealty (rojo)
+                /// Sea cual sea el resultado, el pipeline continua la ejecución del resto de etapas.
+                /// Pasos:
+                /// 1. Se lanza flake8 y se guardan los resultado en el fichero flake8.out. Se añade exit-zero para que flake8 termine correctamente aunque falle.
+                /// 2. Con recordIssues del plugin Warnings-NG se aplican los qualityGates.
+                
+                stage('Static') {
+                    agent {label 'agent_1'}
+                    steps {
+                        sh 'whoami'
+                        sh 'hostname'
+                        echo WORKSPACE
+                        unstash name:'code'
+                        sh '''
+                            export PYTHONPATH=$WORKSPACE
+                            flake8 --exit-zero --format=pylint app > flake8.out
+                        '''
+                        recordIssues qualityGates: [[integerThreshold: 8, threshold: 8.0, type: 'TOTAL'], [criticality: 'FAILURE', integerThreshold: 10, threshold: 10.0, type: 'TOTAL']], sourceCodeRetention: 'LAST_BUILD', tools: [flake8(pattern: 'flake8.out')]
+                    }
+                }
+                
                 /// Etapa de lanzar las prueba unitarias con pytest
                 /// No se utiliza ningún baremo para estableces si las pruebas han sido satisfactorias o no
                 /// La etapa siempre se marca en verde aunque el falle
@@ -37,13 +41,19 @@ pipeline {
                 ///    con los test que queremos ejecutar. Los resultados se guardan en result-unit.xml
                 /// 4. Se llama al plugin JUnit para mostrar los resultados de los tests
                 stage('Unit') {
+                    agent {label 'agent_1'}
                     steps {
+                        sh 'whoami'
+                        sh 'hostname'
+                        echo WORKSPACE
+                        unstash name:'code'
                         catchError(buildResult: 'SUCCESS', stageResult: 'SUCCESS') {
                             sh '''                                        
                                 export PYTHONPATH=$WORKSPACE
                                 coverage run --branch --source=app --omit=app/__init__.py,app/api.py -m pytest --junitxml=result-unit.xml test/unit
                             '''
                             junit 'result-unit.xml' 
+                            stash name:'coverage', includes:'coverage'
                         }
                     }
                 }
@@ -60,7 +70,12 @@ pipeline {
                 /// 5. Se lanzan los test de integración con pytest y se guardan los resultados en result-rest.xml
                 /// 6. Se llama al plugin JUnit para mostrar los resultados de los tests
                 stage('Rest') {
+                    agent {label 'agent_2'}
                     steps {
+                        sh 'whoami'
+                        sh 'hostname'
+                        echo WORKSPACE
+                        unstash name:'code'
                         catchError(buildResult: 'SUCCESS', stageResult: 'SUCCESS') {
                             sh '''
                                 export PYTHONPATH=$WORKSPACE
@@ -70,12 +85,12 @@ pipeline {
                                 
                                 # 10 reintentos para ver si wiremock está levantado
                                 for i in $(seq 1 10); do
-                                  nc -z localhost 9090 && break
-                                  echo "Waiting for WireMock... try $i/10"
-                                  sleep 1
+                                    nc -z localhost 9090 && break
+                                    echo "Waiting for WireMock... try $i/10"
+                                    sleep 1
                                 done || {
-                                  echo "WireMock not available"
-                                  exit 1
+                                    echo "WireMock not available"
+                                    exit 1
                                 }
                                 
                                 pytest --junitxml=result-rest.xml test/rest
@@ -83,73 +98,85 @@ pipeline {
                             junit 'result-rest.xml'
                         }
                     }
-                }        
-            }
-        }
-        
-        
-        /// Etapa para las pruebas de cobertura
-        /// Si la cobertura por línea está entre 80% y 95%, la etapa y el build se marcan como unstable (naranja)
-        /// Si la cobertura por línea está es 95% o mayor, la etapa y el build se marcan como unhealty (rojo)
-        /// Si la cobertura por ramas está entre 80% y 90%, la etapa y el build se marcan como unstable (naranja)
-        /// Si la cobertura por ramas está es 90% o mayor, la etapa y el build se marcan como unhealty (rojo)
-        /// Sea cual sea el resultado, el pipeline continua la ejecución del resto de etapas.
-        /// Para evitar repetir las pruebas unitarias, la cobertura se ejuta en la etapa de tests unitarios y en esta
-        /// se muestran los resultados y se aplican los quality gates.
-        /// Pasos:
-        /// 1. Como ya se ejecutó la cobertura, solo se genera un coverage.xml con los resultados.
-        /// 2. Con recordCoverage del plugin Cobertura se aplican los qualityGates.
-        stage("Coverage") {
-            steps {
-                sh '''
-                    coverage xml
-                '''
-                recordCoverage qualityGates: [[criticality: 'NOTE', integerThreshold: 95, metric: 'LINE', threshold: 95.0], [criticality: 'ERROR', integerThreshold: 85, metric: 'LINE', threshold: 85.0], [criticality: 'ERROR', integerThreshold: 80, metric: 'BRANCH', threshold: 80.0], [criticality: 'NOTE', integerThreshold: 90, metric: 'BRANCH', threshold: 90.0]], tools: [[parser: 'COBERTURA', pattern: 'coverage.xml']]
-            }
-        }
+                }
 
-        /// Etapa para lanzar las pruebas de seguridad con bandit
-        /// Si se encuentran entre 2 y 3 hallazgos, la etapa y el build se marcan como unstable (naranja)
-        /// Si se encuentran 4 o más hallazgos, la etapa y el build se marcan como unhealty (rojo)
-        /// Sea cual sea el resultado, el pipeline continua la ejecución del resto de etapas.
-        stage("Security") {
-            steps {
-                sh '''
-                   export PYTHONPATH=$WORKSPACE
-                   bandit --exit-zero -r . -f custom -o bandit.out --msg-template "{abspath}:{line}: [{test_id}] {msg}" 
-                '''
-                recordIssues tools: [pyLint(name: 'Bandit', pattern: 'bandit.out')], qualityGates: [[integerThreshold: 2, threshold: 2.0, type: 'TOTAL'], [criticality: 'FAILURE', integerThreshold: 4, threshold: 4.0, type: 'TOTAL']]
-            }
-        }
-
-        /// Etapa para las pruebas de rendimiento con JMeter
-        /// Se incluye un test plan en el 5 hilos realizan 40 llamadas al microservicio de suma y 40 al microservicio de resta.
-        /// Pasos:
-        /// 1. Se levanta el servicio de flask
-        /// 3. Con un bucle for se espera que flask esté disponible un máximo de 10 reintentos.
-        /// 4. Se lanza JMeter con el plan test/jmeter/flask.jmx y se guardan los resultados en flask.jtl.
-        /// 5. Con perfReport del plugin perfomance se lee flask.jtl para visualizar los resultados.
-        stage("Performance"){
-            steps {
-                sh '''
-                    export PYTHONPATH=$WORKSPACE
-                    export FLASK_APP=app/api.py
-                    flast run &
-                    
-                    # 10 reintentos para comprobar que Flask está levantado
-                    for i in $(seq 1 10); do
-                      nc -z localhost 5000 && break
-                      echo "Waiting for Flask... try $i/10"
-                      sleep 1
-                    done || {
-                      echo "Flask not available"
-                      exit 1
+                /// Etapa para lanzar las pruebas de seguridad con bandit
+                /// Si se encuentran entre 2 y 3 hallazgos, la etapa y el build se marcan como unstable (naranja)
+                /// Si se encuentran 4 o más hallazgos, la etapa y el build se marcan como unhealty (rojo)
+                /// Sea cual sea el resultado, el pipeline continua la ejecución del resto de etapas.
+                stage("Security") {
+                    agent {label 'agent_1'}
+                    steps {
+                        sh 'whoami'
+                        sh 'hostname'
+                        echo WORKSPACE
+                        unstash name:'code'
+                        sh '''
+                        export PYTHONPATH=$WORKSPACE
+                        bandit --exit-zero -r . -f custom -o bandit.out --msg-template "{abspath}:{line}: [{test_id}] {msg}" 
+                        '''
+                        recordIssues tools: [pyLint(name: 'Bandit', pattern: 'bandit.out')], qualityGates: [[integerThreshold: 2, threshold: 2.0, type: 'TOTAL'], [criticality: 'FAILURE', integerThreshold: 4, threshold: 4.0, type: 'TOTAL']]
                     }
-                    
-                    ~/apache-jmeter-5.6.3/bin/jmeter.sh -n -t test/jmeter/flask.jmx -f -l flask.jtl
-                '''
-                perfReport sourceDataFiles: 'flask.jtl'
+                }
+                /// Etapa para las pruebas de cobertura
+                /// Si la cobertura por línea está entre 80% y 95%, la etapa y el build se marcan como unstable (naranja)
+                /// Si la cobertura por línea está es 95% o mayor, la etapa y el build se marcan como unhealty (rojo)
+                /// Si la cobertura por ramas está entre 80% y 90%, la etapa y el build se marcan como unstable (naranja)
+                /// Si la cobertura por ramas está es 90% o mayor, la etapa y el build se marcan como unhealty (rojo)
+                /// Sea cual sea el resultado, el pipeline continua la ejecución del resto de etapas.
+                /// Para evitar repetir las pruebas unitarias, la cobertura se ejuta en la etapa de tests unitarios y en esta
+                /// se muestran los resultados y se aplican los quality gates.
+                /// Pasos:
+                /// 1. Como ya se ejecutó la cobertura, solo se genera un coverage.xml con los resultados.
+                /// 2. Con recordCoverage del plugin Cobertura se aplican los qualityGates.
+                stage("Coverage") {
+                    agent {label 'agent_1'}
+                    steps {
+                        sh 'whoami'
+                        sh 'hostname'
+                        echo WORKSPACE
+                        unstash name:'coverage'
+                        sh '''
+                            coverage xml
+                        '''
+                        recordCoverage qualityGates: [[criticality: 'NOTE', integerThreshold: 95, metric: 'LINE', threshold: 95.0], [criticality: 'ERROR', integerThreshold: 85, metric: 'LINE', threshold: 85.0], [criticality: 'ERROR', integerThreshold: 80, metric: 'BRANCH', threshold: 80.0], [criticality: 'NOTE', integerThreshold: 90, metric: 'BRANCH', threshold: 90.0]], tools: [[parser: 'COBERTURA', pattern: 'coverage.xml']]
+                    }
+                }
+                /// Etapa para las pruebas de rendimiento con JMeter
+                /// Se incluye un test plan en el 5 hilos realizan 40 llamadas al microservicio de suma y 40 al microservicio de resta.
+                /// Pasos:
+                /// 1. Se levanta el servicio de flask
+                /// 3. Con un bucle for se espera que flask esté disponible un máximo de 10 reintentos.
+                /// 4. Se lanza JMeter con el plan test/jmeter/flask.jmx y se guardan los resultados en flask.jtl.
+                /// 5. Con perfReport del plugin perfomance se lee flask.jtl para visualizar los resultados.
+                stage("Performance"){
+                    agent {label 'agent_2'}
+                    steps {
+                        sh 'whoami'
+                        sh 'hostname'
+                        echo WORKSPACE
+                        unstash name:'code'
+                        sh '''
+                            export PYTHONPATH=$WORKSPACE
+                            export FLASK_APP=app/api.py
+                            flast run &
+                            
+                            # 10 reintentos para comprobar que Flask está levantado
+                            for i in $(seq 1 10); do
+                            nc -z localhost 5000 && break
+                            echo "Waiting for Flask... try $i/10"
+                            sleep 1
+                            done || {
+                            echo "Flask not available"
+                            exit 1
+                            }
+                            
+                            ~/apache-jmeter-5.6.3/bin/jmeter.sh -n -t test/jmeter/flask.jmx -f -l flask.jtl
+                        '''
+                        perfReport sourceDataFiles: 'flask.jtl'
+                    }
+                }
             }
         }
-     }
+    }
 }
